version: '3.8'

services:
  prod-api:
    container_name: nestjs-api
    image: nestjs-api-img
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3333:3333
    # volumes:
    #   - .:/usr/src/app
    #   - /usr/src/app/node_modules
    restart: unless-stopped
    networks:
      - houseTalker
    depends_on:
      - prod-db
    env_file:
      - .prod.env
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    env_file:
      - .env
    volumes:
      - web_data_dev:/var/lib/postgresql/data
    networks:
      - houseTalker
  prod-db:
    image: postgres:13
    ports:
      - 5435:5432
    env_file:
      - .prod.env
    volumes:
      - web_data:/var/lib/postgresql/data
    networks:
      - houseTalker
networks:
  houseTalker:
volumes:
  web_data:
  web_data_dev:
